CREATE TABLE IF NOT EXISTS users (
    id BIGSERIAL PRIMARY KEY,
    username VARCHAR(45) UNIQUE NOT NULL,
    password VARCHAR(128) NOT NULL
);
CREATE TABLE IF NOT EXISTS shopping_lists (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(45) NOT NULL,
    user_id BIGINT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE TABLE IF NOT EXISTS items (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(45) NOT NULL,
    quantity NUMERIC(10,2) NOT NULL,
    list_id BIGINT NOT NULL,
    FOREIGN KEY (list_id) REFERENCES shopping_lists (id)
);
